In [10]:
import numpy as np

#A is the given matrix that we need to find the LU decomposition of...
#Q1 
rows=4
columns=2
A=np.array([2,0,1,4,3,2,6,5]).reshape(rows,columns)
#A=np.array([2,3,1,4,5,2,6,7,3]).reshape(rows,columns)
no_of_zeroes=np.count_nonzero(A==0)

#So we can see that the matrix is not sparse...
#let us proceed with the basic Do-little factorization

L=np.diag(np.ones(rows))
U=np.zeros((rows,columns))

for i in range(rows):
    #Finding the i'th row of L
    for m in range(0,min(i,columns)):
        s=0
        for t in range(0,m):
            s=s+L[i][t]*U[t][m]
        if(U[m][m]==0):
            continue
        L[i][m]=(A[i][m]-s)/U[m][m]

    #Finding the i'th row of U
    for j in range(i,columns):
        s=0
        for k in range(0,i):
            s=s+L[i][k]*U[k][j]  
        U[i][j]=(A[i][j]-s)/L[i][i]
print(L)
print(U)
print(A)
print(np.dot(L,U))
print(no_of_zeroes)

[[1.   0.   0.   0.  ]
 [0.5  1.   0.   0.  ]
 [1.5  0.5  1.   0.  ]
 [3.   1.25 0.   1.  ]]
[[2. 0.]
 [0. 4.]
 [0. 0.]
 [0. 0.]]
[[2 0]
 [1 4]
 [3 2]
 [6 5]]
[[2. 0.]
 [1. 4.]
 [3. 2.]
 [6. 5.]]
1
