In [8]:
import numpy as np
import pandas as pd

x=np.array([[1,2,3,4,5,6,7,8,9,45],
           [0,1,2,3,4,5,6,7,8,36],
           [0,0,1,2,3,4,5,6,7,28],
           [0,0,0,1,2,3,4,5,6,21],
           [0,0,0,0,1,2,3,4,5,15],
           [0,0,0,0,0,1,2,3,4,10],
           [0,0,0,0,0,0,1,2,3,6],
           [0,0,0,0,0,0,0,1,2,3],
           [0,0,0,0,0,0,0,0,1,1]])
solution=[x[8][9]/x[8][8]]
for i in range(7,-1,-1):
    temp=0
    for j in range(1,len(solution)+1):
        temp=temp+x[i][-j-1]*solution[j-1]
    solution.append((x[i][-1]-temp)/x[i][i-10])
print(solution)
print(len(x[0]))


[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
10


In [61]:
import numpy as np

def pivot(i, j, x):
    x[[i, j]] = x[[j, i]]  # Swap rows i and j

def div(i, val, x):
    x[i] /= val  # Divide row i by val

def reduce(j, i, val, x):
    x[j] -= val * x[i]  # Subtract row i * val from row j

def rref(x):
    rows, cols = x.shape
    for i in range(rows):
        # Pivoting
        index = np.argmax(abs(x[i:, i])) + i
        if x[index, i] == 0:
            continue  # Skip if pivot is zero
        pivot(i, index, x)
        div(i, x[i, i], x)
        
       
    return x

x = np.array([[1, 1, 1, 1, 1, 1, 13],
              [2, 3, 2, 0, 0, 5, 11],
              [0, 0, 3, -3, 1, 1, 8],
              [1, 1, 10, 3, 0, 0, 2],
              [3, 5, 12, 0, 0, 0, 1],
              [0, 0, 1, 1, 1, 1, 10]], dtype=float)

print("Original matrix:")
print(x)

x = rref(x)

print("RREF Form:")
print(np.array_str(x,precision=2))


Original matrix:
[[ 1.  1.  1.  1.  1.  1. 13.]
 [ 2.  3.  2.  0.  0.  5. 11.]
 [ 0.  0.  3. -3.  1.  1.  8.]
 [ 1.  1. 10.  3.  0.  0.  2.]
 [ 3.  5. 12.  0.  0.  0.  1.]
 [ 0.  0.  1.  1.  1.  1. 10.]]
RREF Form:
[[ 1.    1.67  4.    0.    0.    0.    0.33]
 [ 0.67  1.    0.67  0.    0.    1.67  3.67]
 [ 0.1   0.1   1.    0.3   0.    0.    0.2 ]
 [-0.   -0.   -1.    1.   -0.33 -0.33 -2.67]
 [ 1.    1.    1.    1.    1.    1.   13.  ]
 [ 0.    0.    1.    1.    1.    1.   10.  ]]


In [34]:
x=np.array([[0,2,-1,1]
            ,[3,-1,2,4]
            ,[4,3,1,7]])
print(x[:,0])
print(x[:,0].argmax())

[0 3 4]
2


In [25]:
print(list(range(3)))

[0, 1, 2]


In [45]:
x = np.array([[1,1,1,1,1,1,13],
              [2,3,2,0,0,5,11],
              [0,0,3,-3,1,1,8],
             [1,1,10,3,0,0,2],
              [3,5,12,0,0,0,1],
              [0,0,1,1,1,1,10]])
print(x[:,0].argmax())

4


In [117]:
def pivot(i,j,x):
    for m in range(len(x[0])):
        x[i][m],x[j][m]=x[j][m],x[i][m]
    return x
def reduce(i,j,val,x):
    for m in range(len(x[0])):
        x[j][m]=x[j][m]-val*x[i][m]
    return x
import pandas as pd
import numpy as np

x = np.array([[1, 1, 1, 1, 1, 1, 13],
              [2, 3, 2, 0, 0, 5, 11],
              [0, 0, 3, -3, 1, 1, 8],
              [1, 1, 10, 3, 0, 0, 2],
              [3, 5, 12, 0, 0, 0, 1],
              [0, 0, 1, 1, 1, 1, 10]], dtype=float)


for t in range(0,len(x)):
    arr=np.array(list(map(abs,x[t:,t])))
    index=arr.argmax()
    x=pivot(t,t+index,x)
    for j in range(t+1,len(x)):
        x=reduce(t,j,x[j][t]/x[t][t],x)
    print(np.array_str(x,precision=2))
    print("\n")
    
#print(np.array_str(x,precision =2))

[[ 3.    5.   12.    0.    0.    0.    1.  ]
 [ 0.   -0.33 -6.    0.    0.    5.   10.33]
 [ 0.    0.    3.   -3.    1.    1.    8.  ]
 [ 0.   -0.67  6.    3.    0.    0.    1.67]
 [ 0.   -0.67 -3.    1.    1.    1.   12.67]
 [ 0.    0.    1.    1.    1.    1.   10.  ]]


[[ 3.    5.   12.    0.    0.    0.    1.  ]
 [ 0.   -0.67  6.    3.    0.    0.    1.67]
 [ 0.    0.    3.   -3.    1.    1.    8.  ]
 [ 0.    0.   -9.   -1.5   0.    5.    9.5 ]
 [ 0.    0.   -9.   -2.    1.    1.   11.  ]
 [ 0.    0.    1.    1.    1.    1.   10.  ]]


[[ 3.    5.   12.    0.    0.    0.    1.  ]
 [ 0.   -0.67  6.    3.    0.    0.    1.67]
 [ 0.    0.   -9.   -2.    1.    1.   11.  ]
 [ 0.    0.    0.    0.5  -1.    4.   -1.5 ]
 [ 0.    0.    0.   -3.67  1.33  1.33 11.67]
 [ 0.    0.    0.    0.78  1.11  1.11 11.22]]


[[ 3.    5.   12.    0.    0.    0.    1.  ]
 [ 0.   -0.67  6.    3.    0.    0.    1.67]
 [ 0.    0.   -9.   -2.    1.    1.   11.  ]
 [ 0.    0.    0.   -3.67  1.33  1.33 11.67]
 

In [75]:
print(abs([2,3,-1,-10

TypeError: bad operand type for abs(): 'list'

In [ ]:
arr=np.array(list(map(abs,x[:,0])))
index=arr.argmax()
x=pivot(0,index,x)
for j in range(1,len(x)):
    x=reduce(0,j,x[j][0]/x[0][0],x)
#print(np.array_str(x,precision=2))
arr=np.array(list(map(abs,x[1:,1])))
index=arr.argmax()
x=pivot(1,1+index,x)
#print(np.array_str(x,precision=2))
for j in range(2,len(x)):
    x=reduce(1,j,x[j][1]/x[1][1],x)
print(np.array_str(x,precision=2))
arr=np.array(list(map(abs,x[2:,2])))
index=arr.argmax()
x=pivot(2,2+index,x)
for j in range(3,len(x)):
    x=reduce(2,j,x[j][2]/x[2][2],x)
print(np.array_str(x,precision=2))

In [121]:
import numpy as np

def pivot(i, j, x):
    x[[i, j]] = x[[j, i]]  # Swap rows i and j

def reduce(j, i, val, x):
    x[j] -= val * x[i]  # Subtract row i * val from row j

def upper_triangular(x):
    rows, cols = x.shape
    for i in range(min(rows, cols)):
        # Pivoting for numerical stability
        index = np.argmax(abs(x[i:, i])) + i
        if x[index, i] == 0:
            continue  # Skip if pivot is zero
        pivot(i, index, x)
        
        # Eliminate entries below the pivot
        for j in range(i + 1, rows):
            if x[j, i] != 0:
                reduce(j, i, x[j, i] / x[i, i], x)
    return x

x = np.array([[1, 1, 1, 1, 1, 1, 13],
              [2, 3, 2, 0, 0, 5, 11],
              [0, 0, 3, -3, 1, 1, 8],
              [1, 1, 10, 3, 0, 0, 2],
              [3, 5, 12, 0, 0, 0, 1],
              [0, 0, 1, 1, 1, 1, 10]], dtype=float)

print("Original matrix:")
print(x)

x = upper_triangular(x)

print("Upper Triangular Form:")
print(np.array_str(x,precision=2))


Original matrix:
[[ 1.  1.  1.  1.  1.  1. 13.]
 [ 2.  3.  2.  0.  0.  5. 11.]
 [ 0.  0.  3. -3.  1.  1.  8.]
 [ 1.  1. 10.  3.  0.  0.  2.]
 [ 3.  5. 12.  0.  0.  0.  1.]
 [ 0.  0.  1.  1.  1.  1. 10.]]
Upper Triangular Form:
[[ 3.00e+00  5.00e+00  1.20e+01  0.00e+00  0.00e+00  0.00e+00  1.00e+00]
 [ 0.00e+00 -6.67e-01  6.00e+00  3.00e+00  0.00e+00  0.00e+00  1.67e+00]
 [ 0.00e+00  0.00e+00 -9.00e+00 -2.00e+00  1.00e+00  1.00e+00  1.10e+01]
 [ 0.00e+00  0.00e+00  0.00e+00 -3.67e+00  1.33e+00  1.33e+00  1.17e+01]
 [ 0.00e+00  0.00e+00  0.00e+00  0.00e+00  1.39e+00  1.39e+00  1.37e+01]
 [ 0.00e+00  0.00e+00  0.00e+00  0.00e+00  1.11e-16  5.00e+00  8.13e+00]]


In [127]:
import numpy as np

def pivot(i, j, x):
    x[[i, j]] = x[[j, i]]  # Swap rows i and j

def reduce(j, i, x):
    factor = x[j, i] / x[i, i]
    x[j] -= factor * x[i]  # Subtract row i * factor from row j

def upper_triangular(x):
    rows, cols = x.shape
    for i in range(rows):
        # Pivoting for numerical stability
        index = np.argmax(abs(x[i:, i])) + i
        if abs(x[index, i]) < 1e-10:
            continue  # Skip if pivot is effectively zero
        pivot(i, index, x)
        
        # Normalize pivot row
        x[i] /= x[i, i]
        
        # Eliminate entries below the pivot
        for j in range(i + 1, rows):
            if abs(x[j, i]) > 1e-10:
                reduce(j, i, x)
    return x

x = np.array([[2,-1,3,4,10],
              [1,1,1,1,5],
              [3,-2,5,2,7],
              [4,3,2,1,8]], dtype=float)

print("Original matrix:")
print(x)

x = upper_triangular(x)

print("Upper Triangular Form:")
print(np.array_str(x,precision=2))


Original matrix:
[[ 2. -1.  3.  4. 10.]
 [ 1.  1.  1.  1.  5.]
 [ 3. -2.  5.  2.  7.]
 [ 4.  3.  2.  1.  8.]]
Upper Triangular Form:
[[ 1.    0.75  0.5   0.25  2.  ]
 [-0.    1.   -0.82 -0.29 -0.24]
 [ 0.    0.    1.    1.17  4.33]
 [ 0.    0.    0.    1.    2.  ]]
